-- =====================================================================
-- Migration 0.21 — SUPPRESSION DE LA TABLE MORTE oauth_identities
-- =====================================================================
--
-- CONTEXTE
-- ─────────
-- La table `oauth_identities` a été créée par
-- `2026_08_10_oauth_phone.sql` (§0.2). Elle devait stocker les identités
-- OAuth (Google). En réalité, les identités Google sont stockées dans
-- `users.auth_provider` + `users.provider_id`, et non dans cette table.
--
-- ÉTAT RÉEL VÉRIFIÉ (audit BOUCLE B, 2026-08-15) — non théorique :
--
--   1. Aucun code PHP ne référence `oauth_identities` :
--        grep -rn "oauth_identities" nexus-api/src nexus-api/public
--      → 0 occurrence.
--   2. Le contrôle de contrat SQL↔PHP (scripts/sql_contract_audit.php)
--      le confirme : « Tables jamais référencées par le code PHP (1) :
--      oauth_identities ».
--   3. Aucun test ne la référence.
--   4. Aucune clé étrangère d'une autre table ne pointe vers elle
--      (information_schema.KEY_COLUMN_USAGE → 0 ligne).
--   5. Aucune donnée : SELECT COUNT(*) → 0 ligne sur la base réelle.
--
-- Google Auth ayant été désactivée (commit 9b6dfbe), cette table ne sera
-- jamais peuplée. La conserver ne ferait que fausser l'inventaire du
-- modèle de données (le README et les audits précédents la listent comme
-- « table morte, à supprimer par migration »).
--
-- CARACTÈRE NON DESTRUCTIF
-- ─────────────────────────
-- Aucune donnée financière ni utilisateur n'est concernée : la table est
-- vide et orpheline. Le DROP est donc sûr.
--
-- =====================================================================

DROP TABLE IF EXISTS `oauth_identities`;
